### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by ghost** [ShinYwings/HDR-Map-Reconstruction-From-a-Single-LDR-Sky-Panoramic-Image-For-Outdoor-Illumination-Estimation#3]
I am really sorry to keep bugging you again and again, but I really wanna request you to help me get it running.

Traceback (most recent call last):
  File "C:\Users\MyPC\Downloads\HDR\inference.py", line 151, in <module>
    pred_hdr = inference(ldr_val, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\Downloads\HDR\inference.py", line 117, in inference
    pred = generator_in_step(ldr, training= False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\framework\func_graph.py", line 1200, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: in user code:

    File "C:\Users\MyPC\Downloads\HDR\inference.py", line 88, in generator_in_step  *
        sunpose_cmf, sunpose_actvMaps= _sun.sunposeEstimation(ldr, training=training)
    File "C:\Users\MyPC\Downloads\HDR\sunpose_net.py", line 65, in sunposeEstimation  *
        fc1 = self.fc1(flat)
    File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 2101, in random_uniform
        return tf.random.stateless_uniform(

    ResourceExhaustedError: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} OOM when allocating tensor with shape[37748736,4096] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:StatelessRandomUniformV2]

**Comment by krisnegi123** [comment]
Hey, actually I am facing quite a very similar issue. Can anyone please help resolve this?

**Comment by ghost** [comment]
Can you please help?

**Comment by ghost** [comment]
???????

**Comment by ShinYwings** [comment]
@krisnegi123 

I have tested it on RTX 3090. You need to ensure your VRAM is larger than 24 GB.
